// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_KRz_56NDeBQlmTAKO2-wfTANiJlSDRo',
    appId: '1:402885852260:web:b441b194567f2421e8f371',
    messagingSenderId: '402885852260',
    projectId: 'lost-and-found-hub-cafa2',
    authDomain: 'lost-and-found-hub-cafa2.firebaseapp.com',
    storageBucket: 'lost-and-found-hub-cafa2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4XjI-Tfgq5DupFbAr5wNEhAZPs4W8F_I',
    appId: '1:402885852260:android:e1677ae4ea7da34ae8f371',
    messagingSenderId: '402885852260',
    projectId: 'lost-and-found-hub-cafa2',
    storageBucket: 'lost-and-found-hub-cafa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8sCjoPpNsQ2kLvE4HAvrmDJbAuapvJA',
    appId: '1:402885852260:ios:969660bf818ed608e8f371',
    messagingSenderId: '402885852260',
    projectId: 'lost-and-found-hub-cafa2',
    storageBucket: 'lost-and-found-hub-cafa2.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8sCjoPpNsQ2kLvE4HAvrmDJbAuapvJA',
    appId: '1:402885852260:ios:969660bf818ed608e8f371',
    messagingSenderId: '402885852260',
    projectId: 'lost-and-found-hub-cafa2',
    storageBucket: 'lost-and-found-hub-cafa2.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_KRz_56NDeBQlmTAKO2-wfTANiJlSDRo',
    appId: '1:402885852260:web:75b574dd876b9ff7e8f371',
    messagingSenderId: '402885852260',
    projectId: 'lost-and-found-hub-cafa2',
    authDomain: 'lost-and-found-hub-cafa2.firebaseapp.com',
    storageBucket: 'lost-and-found-hub-cafa2.firebasestorage.app',
  );

}